[[exercises]]
title = "Question 5 in Winter 2020 Midterm Exam"
difficulty = "Easy"
table = false
multipart= false
type = "tracing"

question = '''
Write the output of the following program.

```{code-block} c
#include <stdio.h>

void skipSpace(int n) {
  for (int i = 1; i <= n; i++) printf(" ");
}

void printLeft(int n) {
  for (int i = 1; i <= n; i++) printf("/");
}

void printRight(int n) {
  for (int i = 1; i <= n; i++) printf("\\");
}

int main(void) {
  const int TSize = 5;
  int i;
  skipSpace(TSize);
  printf("*\n");
  for (i = 0; i < TSize - 2; i++) {
    skipSpace(TSize - 1 - i);
    printLeft(i + 1);
    printf("|");
    printRight(i + 1);
    printf("\n");
  }
  skipSpace(TSize);
  printf("|");
  return 0;
}
'''
answer = '''
     *
    /|\
   //|\\
  ///|\\\
     |
'''


[[exercises]]
title = "Question 4 in Winter 2022 Midterm Exam"
difficulty = "Easy"
type = "function programming"
table = false
multipart= false

question = '''
The following function is called with three distinct characters and returns the middle character, e.g., if 'a', 'b', and 'c' is passed as arguments to the function, it returns 'b'. Rewrite this function such that it only uses one return and one if statement.

```{code-block} c
char median(char a, char b, char c) {
  if (a < b) {
    if (b < c) {
      return b;
    } else if (a < c) {
      return c;
    } else {
      return a;
    }
  }
  if (c < b) {
    return b;
  }
  if (a < c) {
    return a;
  }
  return c;
}
```

'''

starter-code = '''
#include <stdio.h>

char median(char a, char b, char c) {

}
'''

answer = '''
#include <stdio.h>

char median(char a, char b, char c) {
  char result = a;
  if ((a < b && b < c) || (c < b && b < a)) {
    result = b;
  } else if ((a < c && c < b) || (b < c && c < a)) {
    result = c;
  }
  return result;
}
'''

main-function = '''
int main(void) {
  char a, b, c;
  // Read three characters from input
  scanf(" %c %c %c", &a, &b, &c);
  // Call the median function and print the result
  printf("%c\n", median(a, b, c));
  return 0;
}
'''

[[exercises.testcases]]
input = "Q2.T1.in"
output = "Q2.T1.out"

[[exercises.testcases]]
input = "Q2.T2.in"
output = "Q2.T2.out"

[[exercises.testcases]]
input = "Q2.T3.in"
output = "Q2.T3.out"


[[exercises]]
title = "Question 11 in Fall 2015 Midterm Exam"
difficulty = "Intermediate"
type = "function programming"
table = false
multipart= false

question = """
Write a C function `reverseDigits`, the prototype of which is given below, that takes an integer argument value, and returns an integer with its digits reversed. For example, if the argument is `1234`, the function will return `4321`.
"""
starter-code = '''
#include <stdio.h>

int reverseDigits(int value) {

}
'''

answer = '''
#include <stdio.h>

int reverseDigits(int value) {
  int sum = 0, lastDigit;
  while (value != 0) {
    lastDigit = value % 10;
    sum = sum * 10 + lastDigit;
    value = value / 10;
  }
  return sum;
}
'''

main-function = '''
int main(void) {
  int value;
  // Read integer from input
  scanf("%d", &value);

  // Call reverseDigits and print result
  printf("%d\n", reverseDigits(value));

  return 0;
}
'''

[[exercises.testcases]]
input = "Q3.T1.in"
output = "Q3.T1.out"

[[exercises.testcases]]
input = "Q3.T2.in"
output = "Q3.T2.out"

[[exercises.testcases]]
input = "Q3.T3.in"
output = "Q3.T3.out"




[[exercises]]
title = "Question 12 in Fall 2015 Midterm Exam"
difficulty = "Challenging"
type = "programming"
table = false
multipart= false

question = '''
In 1706, John Machin, then a professor in London UK, devised a formula for calculating $\pi$:

$\frac{\pi}{4} = 4 \cdot \arctan(\frac{1}{5}) − \arctan(\frac{1}{239})$

where the `arctan` values can be calculated using the following formula:

$\arctan(x) = x − \frac{x^3}{3} + \frac{x^5}{5} - \frac{x^7}{7} + \frac{x^9}{9} \dots - \frac{x^{299}}{299} + \frac{x^{301}}{301}$

Write a C program that calculates and prints $\\pi$ using this method, printing $10$ digits after the decimal point. You must define your own function called `arctan` to compute the `arctan` values, and you are not allowed to use the `atan` function from the `math` library. When your program is run, its output should be (up to 10 decimal places):

<pre>
Pi = 3.1415926536
</pre>
'''

starter-code = '''
#include <stdio.h>
#include <math.h>

int main(void) {

}
'''

answer = '''
#include <stdio.h>
#include <math.h>

double arctan(double x) {
  int sign = 1;
  double sum = 0;
  for (int i = 1; i <= 301; i += 2) {
    sum += sign * pow(x, i) / i;
    if (sign == 1)
      sign = -1;
    else
      sign = 1;
    // or sign = -sign;
  }
  return sum;
}
int main(void) {
  printf("Pi = %.10lf\n", (4 * arctan(1 / 5.0) - arctan(1 / 239.0)) * 4);
  return 0;
}
'''

[[exercises.testcases]]
input = "Q4.T1.in"
output = "Q4.T1.out"



[[exercises]]
title = "Question 9 in Winter 2020 Midterm Exam"
difficulty = "Challenging"
type = "function programming"
table = false
multipart= false

question = """
A pythagorean triple is a triple of integers $(x, y, z)$ such that $x^2 + y^2 = z^2$. 

Complete this function that takes a single positive integer `x` as an argument and prints three positive integer values `x`, `y` and `z` such that:
1. $x^2 + y^2 = z^2$
2. $y > 0$ and $y < 100$
3. $y < z$.

If there is no triple that satisfies these conditions print “no solution exists.”

"""
starter-code = '''
#include <stdio.h>
#include <math.h>

void pythagoreanTriples (int x) {
}
'''

answer = '''
#include <stdio.h>
#include <math.h>

void pythagoreanTriples(int x) {
  for (int y = 1; y < 100; y++) {
    int zz = x * x + y * y;
    int z = sqrt(x * x + y * y);
    if ((z > y) && (sqrt(zz) == z)) {
      printf("x = %d, y = %d, z = %d\n", x, y, z);
      return;
    }
  }
  printf("no solution exists.\n");
}
'''

main-function = '''
int main(void) {
  int x;
  scanf("%d", &x);
  pythagoreanTriples(x);
  return 0;
}
'''


[[exercises.testcases]]
input = "Q5.T1.in"
output = "Q5.T1.out"

[[exercises.testcases]]
input = "Q5.T2.in"
output = "Q5.T2.out"

[[exercises.testcases]]
input = "Q5.T3.in"
output = "Q5.T3.out"

[[exercises.testcases]]
input = "Q5.T4.in"
output = "Q5.T4.out"

