[[exercises]]
title = "Question 10 in Winter 2017 Final Exam"
difficulty = "Intermediate"
type = "programming"
table = false
multipart= false

question = """

You are to write a function that sets a rectangular portion of a 2-dimensional array to a specific value. The function takes the following as input parameters: an integer 1000 $\times$ 1000 2-dimensional array called `A`, four integer parameters named `rowStart`, `rowEnd`, `colStart`, and `colEnd` and an integer parameter `value`.

The purpose of the function is to set the value of the array elements in `A` beginning with `A[rowStart][colStart]` and ending with `A[rowEnd][colEnd]` to be the value `value`. The
picture below illustrates that the shaded portion of the array should have its elements changed to value, for the specific example given:

![Access each element in 2D array](../../_images/winter17-q10-image.png)

However, this function is to he used by students in a first year C programming course, and those students are well-known for writing code that has errors. For example, they often attempt to access elements of an array outside of its defined bounds, among other problems. Therefore, your function should check that the inputs to the function are correct before performing the above operation. You must determine, through the reading of this question, what would make the inputs `rowStart`, `rowEnd`, `colStart`, `colEnd` and `value` correct. (You can assume that the array `A` is passed in correctly.)

The function should return a boolean result that is set to `true` if the inputs are valid, and `false` if they are not. In the case that the inputs are not valid, the setting of the values of the array should not be attempted.

**IMPORTANT:** Your solution, in addition to the code for the function described above, should also show how you would call this function from the main function, and **make use of its return value**. That is, you should show the call to the function (with appropriately declared variables, and gathering input from the user for `rowStart`, `rowEnd`, `colStart`, `colEnd` and `value`) and make appropriate use of the returned boolean value.
"""

starter-code = '''
#include <stdbool.h>
#include <stdio.h>

bool initSectionInArray(                   ) {
                  
}

int main(void) {

}
'''

answer = '''
#include <stdbool.h>
#include <stdio.h>
bool checkBound(int start, int end) {
  // not every check here is strictly necessary
  if (start > end) return false;
  if (start < 0 || start > 999) return false;
  if (end < 0 || end > 999) return false;
  return true;
}
bool initSectionInArray(int A[1000][1000], int rowStart, int rowEnd,
                        int colStart, int colEnd, int value) {
  if (!checkBound(rowStart, rowEnd)) return false;
  if (!checkBound(colStart, colEnd)) return false;
  for (int i = rowStart; i <= rowEnd; i++)
    for (int j = colStart; j <= colEnd; j++) A[i][j] = value;
  return true;
}
int main(void) {
  int x1, x2, y1, y2, v, a[1000][1000];
  printf("Enter x1, x2, y1, y2, v\n");
  scanf("%d%d%d%d%d", &x1, &x2, &y1, &y2, &v);
  if (initSectionInArray(a, x1, x2, y1, y2, v))
    printf("Success!\n");
  else {
    printf("Failure - something wrong with input indices\n");
    return (1);
  }
  return 0;
}
'''


