[[exercises]]
title = "Question 1.7 in Fall 2011"
difficulty = "Easy"
table = false
multipart= false
type = "function programming"

question = """
Your task is to complete the function below so that it contains a non-recursive implementation of the binary search algorithm. The parameter `values` is an array of `int` type variables. The items in the values array have been sorted into descending (non-ascending) order. Parameter `n` is the number of elements in the `values` array. Parameter `item` is the item being searched for in the values array.

The function should return -1 if `item` is not found in the array. Otherwise, the function should return the index position within the array at which `item` is found.

**Important:** your function should assume that `values` is a sorted array in descending (non-ascending) order.

**Important:** Your solution must **not** use recursion.
"""

starter-code = '''
#include <stdio.h>

int binSearch(int values[], int n, int item) {
  int left = 0;
  int right = n - 1;
  while (left <= right) {
    int middle = (left + right) / 2;
    if (item == values[middle]) return middle;

    // WRITE YOUR CODE HERE:

  }
}
'''

answer = '''
#include <stdio.h>

int binSearch(int values[], int n, int item) {
  int left = 0;
  int right = n - 1;
  while (left <= right) {
    int middle = (left + right) / 2;
    if (item == values[middle]) return middle;
    // SOLUTION:
    if (item < values[middle])
      left = middle + 1;
    else
      right = middle - 1;
  }
  return -1;
}
'''

main-function = '''
int main(void) {
    int n, item;
    scanf("%d", &n);

    int values[n];
    for (int i = 0; i < n; i++) {
        scanf("%d", &values[i]);
    }

    scanf("%d", &item);

    int index = binSearch(values, n, item);
    printf("%d\n", index);

    return 0;
}
'''

[[exercises.testcases]]
input = "Q1.T1.in"
output = "Q1.T1.out"

[[exercises.testcases]]
input = "Q1.T2.in"
output = "Q1.T2.out"

[[exercises.testcases]]
input = "Q1.T3.in"
output = "Q1.T3.out"

[[exercises.testcases]]
input = "Q1.T4.in"
output = "Q1.T4.out"

[[exercises.testcases]]
input = "Q1.T5.in"
output = "Q1.T5.out"

[[exercises.testcases]]
input = "Q1.T6.in"
output = "Q1.T6.out"
