[[questions]]

prompt = "Write a C program that prints \"Hello, World!\""

programming = true
tracing = false

code = '''#include <stdio.h>

int main(void){
    printf("");
    return 0;
}'''

answer = []

distractors = []

explainations = []

[[questions.testcases]]
input = [""]
output = ["Hello, World!"]


[[questions]]

prompt = "In the box provided below, write the output generated after the following program is completely executed."

programming = false
tracing = true

code = '''#include <stdio.h>
int main(void) {
  int first = 1, second = 2, data[4] = {10, 20, 30, 40};
  int *third = &second, *fourth = &first, *fifth = data + first + 1;
  (*third)++;
  (*fourth)++;
  data[second] = *fifth + first + *third + *fourth;
  printf("first = %d, second = %d, third = %d, fourth = %d, fifth = %d\n",
         first, second, *third, *fourth, *fifth);
  for (int i = 0; i < 4; i++) {
    printf("%d, ", data[i]);
  }
  printf("\n");
  return 0;
}
'''

answer = """first = 2, second = 3, third = 3, fourth = 2, fifth = 30
10, 20, 30, 37,"""

distractors = []

explainations = []


[[questions]]

prompt = "What will be printed when the following C program is executed?"

programming = false
tracing = true

code = '''int main(void) {
  int first = 1, second = 10;
  int *pointerToFirst, *pointerToSecond;

  pointerToFirst = &first;
  pointerToSecond = &second;
  *pointerToFirst = *pointerToSecond - *pointerToFirst;
  *pointerToSecond = *pointerToSecond - *pointerToFirst;
  *pointerToFirst = *pointerToSecond + *pointerToFirst;
  printf("%d, %d\n", first, second);
}
'''

answer = """10, 1"""

distractors = []

explainations = []


[[questions]]

prompt = "Write a C program that reads two integers from the user and prints their sum."

programming = true
tracing = false

code = '''#include <stdio.h>

int main() {
    int a, b;

    // printf("Enter two integers:");

    // Read two integers from one line
    scanf("%d %d", &a, &b);

    // Print the sum
    printf("%d\n", a + b);

    return 0;
}
'''

answer = []

distractors = []

explainations = []

[[questions.testcases]]
input = ["3 5"]
output = ["""Enter two integers:
8"""]


[[questions]]

prompt = "Write a program that converts inches to centimeters. The program should prompt the user for a number of inches and then output the equivalent number of centimeters. The conversion factor is 2.54 centimeters per inch."

programming = true
tracing = false

code = '''// Description: This program convert inches to centimeters
#include <stdio.h>

int main(void){
  // Declare variables
  const double InchesToCm = 2.54;
  double inputInches, outputCm;

  // Prompt user for input
  scanf("%lf", &inputInches);
  // Convert inches to centimeters
  outputCm = inputInches * InchesToCm;
 
  // Display output in 2 decimal places
  printf("The number of centimeters is %.2lf\n", outputCm);
  return 0;
}'''

answer = []

distractors = []

explainations = []

[[questions.testcases]]
input = ["10"]
output = ["The number of centimeters is 25.40"]

[[questions.testcases]]
input = ["5"]
output = ["The number of centimeters is 12.70"]

[[questions.testcases]]
input = ["3.4"]
output = ["The number of centimeters is 8.64"]


[[questions]]

prompt = "Let's say you want to design a \"micro\" computer with exactly 64KB of memory. How many bits would you need to address each byte of memory?"

programming = false 
tracing = false

code = ""

output = ""

answer = [3]

distractors = ["4 bits", "8 bits", "12 bits", "16 bits"]

explainations = [
'''
4 bits is incorrect. The memory is organized in cells. Each cell stores a byte. Each cell has an address. This makes the memory byte-addressable. This means at each address only one byte is stored.

To address 64KB of memory, we can use a 16-bit address. This allows us to represent 2^16 = 65,536 unique addresses, which covers the range of 64KB.
''',
'''
8 bits is incorrect. The memory is organized in cells. Each cell stores a byte. Each cell has an address. This makes the memory byte-addressable. This means at each address only one byte is stored.

To address 64KB of memory, we can use a 16-bit address. This allows us to represent 2^16 = 65,536 unique addresses, which covers the range of 64KB.
''',
'''
12 bits is incorrect. The memory is organized in cells. Each cell stores a byte. Each cell has an address. This makes the memory byte-addressable. This means at each address only one byte is stored.

To address 64KB of memory, we can use a 16-bit address. This allows us to represent 2^16 = 65,536 unique addresses, which covers the range of 64KB.
''',
'''
16 bits is correct. The memory is organized in cells. Each cell stores a byte. Each cell has an address. This makes the memory byte-addressable. This means at each address only one byte is stored.

To address 64KB of memory, we can use a 16-bit address. This allows us to represent 2^16 = 65,536 unique addresses, which covers the range of 64KB.
'''
]
