[[questions]]

prompt = "Write a C program that prints \"Hello, World!\" or \"Hello\""

programming = true

code = '''#include <stdio.h>

int main(void){
    printf("");
    return 0;
}'''

output = ["Hello, World!"]

answer = []

distractors = []

explainations = []


[[questions]]

prompt = "Write a C program that prints \"pizza\""

programming = true

code = '''// Description: This program convert inches to centimeters
#include <stdio.h>

int main(void){
  // Declare variables
  const double InchesToCm = 2.54;
  double inputInches, outputCm;

  // Prompt user for input
  scanf("%lf", &inputInches);
  // Convert inches to centimeters
  outputCm = inputInches * InchesToCm;
 
  // Display output in 2 decimal places
  printf("The number of centimeters is %.2lf\n", outputCm);
  return 0;
}'''

output = ["The number of centimeters is 25.40", "The number of centimeters is 12.70"]

input = ["10", "5"]

answer = []

distractors = []

explainations = []


[[questions]]

prompt = "Let's say you want to design a \"micro\" computer with exactly 64KB of memory. How many bits would you need to address each byte of memory?"

programming = false 

code = ""

output = ""

answer = [3]

distractors = ["4 bits", "8 bits", "12 bits", "16 bits"]

explainations = [
'''
4 bits is incorrect. The memory is organized in cells. Each cell stores a byte. Each cell has an address. This makes the memory byte-addressable. This means at each address only one byte is stored.

To address 64KB of memory, we can use a 16-bit address. This allows us to represent 2^16 = 65,536 unique addresses, which covers the range of 64KB.
''',
'''
8 bits is incorrect. The memory is organized in cells. Each cell stores a byte. Each cell has an address. This makes the memory byte-addressable. This means at each address only one byte is stored.

To address 64KB of memory, we can use a 16-bit address. This allows us to represent 2^16 = 65,536 unique addresses, which covers the range of 64KB.
''',
'''
12 bits is incorrect. The memory is organized in cells. Each cell stores a byte. Each cell has an address. This makes the memory byte-addressable. This means at each address only one byte is stored.

To address 64KB of memory, we can use a 16-bit address. This allows us to represent 2^16 = 65,536 unique addresses, which covers the range of 64KB.
''',
'''
16 bits is correct. The memory is organized in cells. Each cell stores a byte. Each cell has an address. This makes the memory byte-addressable. This means at each address only one byte is stored.

To address 64KB of memory, we can use a 16-bit address. This allows us to represent 2^16 = 65,536 unique addresses, which covers the range of 64KB.
'''
]